[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.2.26"
edition = "2024"
license = "MIT"
authors = ["Jeremy Banks <_@jeremy.ca>"]
repository = "https://github.com/jeremyBanks/0dmg"
publish = false

[workspace.dependencies]
zerodmg-codes = { version = "0.2.26", path = "crates/zerodmg-codes" }
zerodmg-emulator = { version = "0.2.26", path = "crates/zerodmg-emulator" }
zerodmg-utils = { version = "0.2.26", path = "crates/zerodmg-utils" }
