#!/bin/bash
set -eux;
CARGO="cargo +nightly";
${CARGO} build;
${CARGO} clean;
for f in zerodmg-*; do
    (
        cd "${f}";
        ${CARGO} clean;
        ${CARGO} fix --allow-dirty;
        ${CARGO} fmt;
        ${CARGO} clippy;
    );
done
${CARGO} fix --allow-dirty;
${CARGO} fmt;
${CARGO} clippy;
