#!/bin/bash
set -eux;
CARGO="cargo +nightly";
function clean {
    ${CARGO} clean;
    for f in zerodmg-*; do
        (
            cd "${f}";
            ${CARGO} clean;
        );
    done
}

clean;
${CARGO} fmt;

clean;
${CARGO} fix --allow-dirty;

clean;
${CARGO} clippy;
