#!/bin/bash

PARENT_CRATE="rust_issue_51798_example_parent";
PARENT_ID="arbitrary_parent_id";

CHILD_CRATE="rust_issue_51798_example_child";
CHILD_ID="arbitrary_child_id";

OUT_DIR="./target"

RUSTC="
rustc +nightly
  --edition=2018
  --crate-type lib
  --out-dir ""$OUT_DIR""
  -L dependency=""$OUT_DIR""";

set -eux;

rm -rfv "$OUT_DIR";
mkdir -pv "$OUT_DIR";

$RUSTC \
  child.rs \
  --crate-name "$CHILD_CRATE" \
  -C metadata="$CHILD_ID" \
  -C extra-filename=-"$CHILD_ID";

$RUSTC \
  parent.rs \
  --crate-name "$PARENT_CRATE" \
  -C metadata="$PARENT_ID" \
  -C extra-filename=-"$PARENT_ID" \
  --extern "$CHILD_CRATE"="$OUT_DIR"/lib"$CHILD_CRATE"-"$CHILD_ID".rlib;
