#!/bin/bash
set -euo pipefail;
clear;
cd "$(dirname ${BASH_SOURCE[0]})";
cargo fmt;
echo;
cargo build --color=always 2>&1;
echo;
cargo test --doc --color=always 2>&1;
cargo test --lib --color=always 2>&1;
echo;
cargo rustdoc --color=always -- --document-private-items 2>&1;
echo;
echo "Internal docs written to: file://$PWD/target/doc/zerodmg_codes/index.html";
echo;
cargo fix --allow-dirty;
echo;
