#!/bin/bash
set -euo pipefail;
cd "$(dirname ${BASH_SOURCE[0]})";
clear;
cargo +nightly fmt 2>&1;
echo;
cargo +nightly build --color=always 2>&1;
echo;
cargo +nightly rustdoc --color=always -- --document-private-items 2>&1;
echo;
echo "Internal docs written to: file://$PWD/target/doc/zerodmg_codes/index.html";
echo;
cargo +nightly fix --allow-dirty 2>&1;
echo;
cargo +nightly test --doc --color=always 2>&1;
cargo +nightly test --lib --color=always 2>&1;
echo;
