#!/bin/bash
set -euo pipefail;
echo; echo; echo; echo; echo; echo; echo; 
clear;
echo; echo; echo; echo; echo; echo; echo; 
clear;
cd "$(dirname ${BASH_SOURCE[0]})";
cargo fmt;
cargo build --color=always 2>&1;
cargo doc --color=always --no-deps 2>&1;
