[package]
name = "zerodmg-codes"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true
description = "pieces of a naive incomplete broken game boy emulator"
readme = "../README.md"

[dependencies]
zerodmg-utils = { version = "0.1.10", path = "../zerodmg-utils" }
derive_more = "0.99"