[package]
name = "zerodmg-emulator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true
description = "pieces of a naive incomplete broken game boy emulator"
readme = "../README.md"

[dependencies]
zerodmg-utils = { version = "0.1.10", path = "../zerodmg-utils" }
zerodmg-codes = { version = "0.1.10", path = "../zerodmg-codes" }
image = "0.19.0"
rand = "0.8"
